name: spilll_icons
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  
  assets:
    - assets/

  fonts:
   - family: SpilllIcons
     fonts:
      - asset: lib/fonts/SpilllIcons.ttf
